### ISSUE TITLE
Painting

### ISSUE THREAD

**Issue by lemcquaid** [lemcquaid/house#1]
- [x] Upstairs bathroom (ceiling with anti-mould paint)
- [x] Spare room one
- [x] Spare room two
- [x] Office
- [x] Hall
- [x] Bedroom door
- [x] Kitchen

**Comment by mikemcquaid** [comment]
From my Mum:

> Painter is called Rab 0131 315 2040

Maybe we get him started on the bedroom door?

**Comment by mikemcquaid** [comment]
Updated the description to clarify we'll get all of the upstairs bathroom painted.

**Comment by mikemcquaid** [comment]
All done.
