### ISSUE TITLE
Garden Gate

### ISSUE THREAD

**Issue by lemcquaid** [lemcquaid/house#20]
- [x] Contact Gus for quote
- [x] Arrange time to get work done
- [x] Get gate painted
- [x] :dog: friendly; Lindsay friendly; new latch

**Comment by mikemcquaid** [comment]
No rush on this I think?

**Comment by lemcquaid** [comment]
Medium term. Might be nice to have it done before summer? I think I have a little more trouble opening it sometimes that you, but it is no urgent by any stretch

**Comment by mikemcquaid** [comment]
All done with new latch :balloon:
