### ISSUE TITLE
Things to do before painter (July/August 2015)

### ISSUE THREAD

**Issue by lemcquaid** [lemcquaid/house#22]
- [x] Electrician (as may put more holes in wall) 
- [x] Joiner (Gus) for upstairs door/door-frame
- [x] Plumber for boiler (as may need re-painted after  
- [x] Remove office desk/cupboards 
- [x] Remove curtain rails in both spare bedrooms  
- [x] Remove all nails in walls in both spare bedrooms  
- [x] Remove hammock 
- [x] Remove shelves in sofa room 
- [x] Ask painter if he can also strip wallpaper on sofa room ceiling  
- [x] Ask painter if he can use the most durable/wipeable type of Dulux 
- [x] Confirm start date for painting

**Comment by lemcquaid** [comment]
We probably want to get going with these things, particularly as you will begin the USA. Next weekend we are free so could maybe take the office down?

**Comment by mikemcquaid** [comment]
:art: was all done, hooray.
