### ISSUE TITLE
Shower (upstairs)

### ISSUE THREAD

**Issue by lemcquaid** [lemcquaid/house#3]
- [x] Remove caddy
- [x] Speak to Sean about getting all sealant cleaned/replaced (between the tiles, fill the holes from the caddy; the sealant between the bottom tiles and shower tray). See email: 

> Hi Lindsay,
> Sorry about the late reply, we've been flooded with work in the last few weeks. There is a few things I'd > need to know before giving you a ballpark figure, give me a call on my mobile and we can discuss them. 
> If the figure is within your budget, I'll be happy to pop over one evening and give you an exact price.
> 07817 828 681 - Sean

- [x] Companies: http://resealscotland.co.uk/index.php?page=reseal-service
http://www.totalcleaningscotland.co.uk/our-services/domestic-cleaning
- [x] get new tension caddy

**Comment by mikemcquaid** [comment]
All done :tada:
