### ISSUE TITLE
Outside space

### ISSUE THREAD

**Issue by lemcquaid** [lemcquaid/house#7]
- [x] Get driveway power washed and re-sanded
- [x] ~~Lock put on garage~~
- [x] ~~Buy tray for final flower bed~~
- [x] Get turf put down
- [x] Weedkiller on decking

**Comment by mikemcquaid** [comment]
Don't think we need the lock or final tray. We'll just get the lawn mown when we get the new mower and put the turf down in spring.

**Comment by mikemcquaid** [comment]
From Mum about turf:

> Name of garden guy is Duncan Peddie 07796872574
> He works for the Great Lawn co. Tell him I am your Mum.

**Comment by lemcquaid** [comment]
agreed

**Comment by mikemcquaid** [comment]
All done until :dog: attacks it
